version: "3"

services:
  php:
    image: dmnlouis/php:${PHP_VERSION}
    profiles: ["php"]
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  php-xdebug:
    image: dmnlouis/php:${PHP_VERSION}-xdebug
    profiles: ["php-xdebug"]
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway

  caddy:
    image: dmnlouis/caddy:2.7
    links:
      - '${PHP_IMAGE}:php'
    depends_on:
      - ${PHP_IMAGE}
    environment:
      SERVER_NAME: ${SERVER_NAME}
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  caddy_data: {}
  caddy_config: {}
  database: {}

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
