version: "3"

services:
  php:
    image: dmnlouis/php:8.2
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  caddy:
    image: caddy:2.7-alpine
    links:
      - php
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME}
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker/caddy/certs:/usr/local/share/ca-certificates
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  caddy_data: {}
  caddy_config: {}
  database: {}

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
